import { createGitHubPr, createAdoPr } from "./git-providers";
import type { PipelineContext } from "./pipeline";

/**
 * Agent 5: PR Creator
 * Creates a branch, pushes the test script, and opens a PR.
 * Routes to GitHub or Azure DevOps based on the repository provider.
 */
export async function runPrCreator(
  ctx: PipelineContext,
  script: string,
  testType: "smoke" | "regression" = "smoke"
): Promise<string> {
  const isRegression = testType === "regression";
  const typeLabel = isRegression ? "regression test" : "smoke test";
  const branchName = `testforge/${typeLabel.replace(" ", "-")}-${ctx.scenarioId.slice(0, 8)}`;
  const fileName = generateFileName(ctx);
  const filePath = ctx.outputFolder
    ? `${ctx.outputFolder}/${fileName}`
    : fileName;
  const prTitle = `test: add ${typeLabel} — ${ctx.inputText.slice(0, 50)}`;
  const prBody = [
    `## TestForge Auto-Generated ${isRegression ? "Regression" : "Smoke"} Test`,
    "",
    `**Application:** ${ctx.applicationName}`,
    `**${isRegression ? "Target URL" : "Scenario"}:** ${ctx.inputText}`,
    "",
    "This test was automatically generated by TestForge's AI agent pipeline.",
  ].join("\n");

  ctx.emit({
    event: "agent_message",
    data: {
      agent: "pr_creator",
      text: `Creating branch: ${branchName}`,
    },
  });

  ctx.emit({
    event: "agent_message",
    data: {
      agent: "pr_creator",
      text: `Pushing ${fileName} to ${filePath}...`,
    },
  });

  let prUrl: string;

  if (ctx.repositoryProvider === "github") {
    const result = await createGitHubPr(
      ctx.repositoryUrl,
      ctx.repositoryPat,
      branchName,
      filePath,
      script,
      prTitle,
      prBody
    );
    prUrl = result.prUrl;
  } else if (ctx.repositoryProvider === "ado") {
    if (!ctx.repositoryOrganization) {
      throw new Error("Azure DevOps requires an organization name");
    }
    const result = await createAdoPr(
      ctx.repositoryUrl,
      ctx.repositoryPat,
      ctx.repositoryOrganization,
      branchName,
      filePath,
      script,
      prTitle,
      prBody
    );
    prUrl = result.prUrl;
  } else {
    throw new Error(`Unsupported repository provider: ${ctx.repositoryProvider}`);
  }

  ctx.emit({
    event: "agent_message",
    data: {
      agent: "pr_creator",
      text: "Pull request created successfully.",
    },
  });

  return prUrl;
}

function generateFileName(ctx: PipelineContext): string {
  const slug = ctx.inputText
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 40)
    .replace(/-$/, "");
  return `${slug}.spec.ts`;
}
